### ISSUE TITLE
Using different fonts

### ISSUE THREAD

**Issue by mzgreen** [StylingAndroid/Rialto#1]
Rialto is really cool, thank you for creating it!

I couldn't find it myself - Is it possible to create a text that uses multiple different fonts?

**Comment by dvdmunckhof** [comment]
I guess [`TypefaceSpan`](https://developer.android.com/reference/android/text/style/TypefaceSpan) would work.

**Comment by StylingAndroid** [comment]
As @dvdmunckhof says: you can use [TypefaceSpan](https://developer.android.com/reference/android/text/style/TypefaceSpan) for this if you're lucky enough to be `minSdkVersion="28"` or higher. If not take a look at Florina's [CustomTypefaceSpan](https://gist.github.com/florina-muntenescu/08d751d843d55b75061039fee4e97931).

While I am working on something font-related, the fundamental behaviour of Rialto already supports this - just use the appropriate span type and it works quite nicely. Therefore I am closing this, as fonts are already supported.
