### ISSUE TITLE
Scary looking logcat entry when extending RialtoActivity

### ISSUE THREAD

**Issue by teal77** [StylingAndroid/Rialto#7]
`AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's`

Is this normal?

**Comment by StylingAndroid** [comment]
It is expected.

Rialto replaces the AppCompat ViewInflator with its own. But the Rialto [ViewInflator extends the AppCompat one](https://github.com/StylingAndroid/Rialto/blob/master/library/src/material/java/androidx/appcompat/app/RialtoViewInflater.kt#L12)
